/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaLogin;
import TelaLogin.GlobalVariables;

/**
 * @author unive
 */
public class TelaPrincipalIMC extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalIMC
     */
    public TelaPrincipalIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HomeImagen = new javax.swing.JLabel();
        AguaImagem = new javax.swing.JLabel();
        IMCText = new javax.swing.JLabel();
        AguaText3 = new javax.swing.JLabel();
        AguaText2 = new javax.swing.JLabel();
        AguaText1 = new javax.swing.JLabel();
        SonoText1 = new javax.swing.JLabel();
        SonoText2 = new javax.swing.JLabel();
        SonoText3 = new javax.swing.JLabel();
        IMCImagem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SonoImagem = new javax.swing.JLabel();
        ExitImagem = new javax.swing.JLabel();
        FundoParaTirarBorda = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HomeText = new javax.swing.JLabel();
        MedidorDeAgua = new javax.swing.JButton();
        IMC = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        TempoDeSono = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ImagenNotificação = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        ImagemPulseFit = new javax.swing.JLabel();
        BotãoNotificação = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PulseFit");
        setMinimumSize(new java.awt.Dimension(1050, 470));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 200, 150, 70);

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 280, 150, 60);

        HomeImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\casa.png")); // NOI18N
        jPanel2.add(HomeImagen);
        HomeImagen.setBounds(10, 40, 60, 70);

        AguaImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\bebida.png")); // NOI18N
        jPanel2.add(AguaImagem);
        AguaImagem.setBounds(0, 200, 60, 64);

        IMCText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        IMCText.setForeground(new java.awt.Color(0, 0, 0));
        IMCText.setText("IMC");
        jPanel2.add(IMCText);
        IMCText.setBounds(90, 140, 40, 20);

        AguaText3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaText3.setForeground(new java.awt.Color(0, 0, 0));
        AguaText3.setText("de");
        jPanel2.add(AguaText3);
        AguaText3.setBounds(90, 220, 30, 24);

        AguaText2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaText2.setForeground(new java.awt.Color(0, 0, 0));
        AguaText2.setText("Água");
        AguaText2.setToolTipText("");
        jPanel2.add(AguaText2);
        AguaText2.setBounds(80, 240, 50, 30);

        AguaText1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaText1.setForeground(new java.awt.Color(0, 0, 0));
        AguaText1.setText("Consumo ");
        jPanel2.add(AguaText1);
        AguaText1.setBounds(60, 190, 90, 40);

        SonoText1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SonoText1.setForeground(new java.awt.Color(0, 0, 0));
        SonoText1.setText("Sono");
        jPanel2.add(SonoText1);
        SonoText1.setBounds(90, 320, 60, 20);

        SonoText2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SonoText2.setForeground(new java.awt.Color(0, 0, 0));
        SonoText2.setText("Gestão");
        jPanel2.add(SonoText2);
        SonoText2.setBounds(80, 280, 60, 20);

        SonoText3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SonoText3.setForeground(new java.awt.Color(0, 0, 0));
        SonoText3.setText("do");
        jPanel2.add(SonoText3);
        SonoText3.setBounds(100, 300, 20, 20);

        IMCImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\balanca (3).png")); // NOI18N
        jPanel2.add(IMCImagem);
        IMCImagem.setBounds(10, 120, 60, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\OneDrive\\Imagens\\PulseFit.jpg")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 110, 150, 80);

        SonoImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\sono-suficiente.png")); // NOI18N
        SonoImagem.setToolTipText("");
        jPanel2.add(SonoImagem);
        SonoImagem.setBounds(10, 280, 70, 60);

        ExitImagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExitImagem.setForeground(new java.awt.Color(0, 0, 0));
        ExitImagem.setText("X");
        jPanel2.add(ExitImagem);
        ExitImagem.setBounds(10, 0, 30, 20);

        FundoParaTirarBorda.setBackground(new java.awt.Color(255, 255, 255));
        FundoParaTirarBorda.setForeground(new java.awt.Color(255, 255, 255));
        FundoParaTirarBorda.setLayout(null);

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FundoParaTirarBorda.add(jLabel7);
        jLabel7.setBounds(0, 30, 150, 50);

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FundoParaTirarBorda.add(jLabel4);
        jLabel4.setBounds(0, 30, 150, 80);

        HomeText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        HomeText.setForeground(new java.awt.Color(0, 0, 0));
        HomeText.setText("Sobre nós");
        FundoParaTirarBorda.add(HomeText);
        HomeText.setBounds(70, 70, 80, 30);

        jPanel2.add(FundoParaTirarBorda);
        FundoParaTirarBorda.setBounds(0, 0, 160, 440);

        MedidorDeAgua.setBackground(new java.awt.Color(255, 255, 255));
        MedidorDeAgua.setForeground(new java.awt.Color(0, 0, 0));
        MedidorDeAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MedidorDeAgua.setBorderPainted(false);
        MedidorDeAgua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MedidorDeAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedidorDeAguaActionPerformed(evt);
            }
        });
        jPanel2.add(MedidorDeAgua);
        MedidorDeAgua.setBounds(0, 190, 150, 80);

        IMC.setBackground(new java.awt.Color(255, 255, 255));
        IMC.setForeground(new java.awt.Color(255, 255, 255));
        IMC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        IMC.setBorderPainted(false);
        IMC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCActionPerformed(evt);
            }
        });
        jPanel2.add(IMC);
        IMC.setBounds(0, 110, 150, 80);

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(null);
        Home.setBorderPainted(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.setNextFocusableComponent(HomeImagen);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel2.add(Home);
        Home.setBounds(0, 40, 150, 70);

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setForeground(new java.awt.Color(0, 0, 0));
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ExitButton);
        ExitButton.setBounds(0, 0, 30, 20);

        TempoDeSono.setBackground(new java.awt.Color(255, 255, 255));
        TempoDeSono.setForeground(new java.awt.Color(255, 255, 255));
        TempoDeSono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TempoDeSono.setBorderPainted(false);
        TempoDeSono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TempoDeSono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempoDeSonoActionPerformed(evt);
            }
        });
        jPanel2.add(TempoDeSono);
        TempoDeSono.setBounds(0, 270, 150, 80);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 150, 680);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Clique na tela para calcular seu IMC");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 10, 340, 21);

        ImagenNotificação.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\cuidado (1).png")); // NOI18N
        ImagenNotificação.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(ImagenNotificação);
        ImagenNotificação.setBounds(150, 0, 32, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Coloque sua altura abaixo:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 110, 230, 21);

        jButton3.setText("ADD");
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 140, 72, 23);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 140, 170, 22);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Coloque seu peso abaixo:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 180, 220, 21);

        jButton4.setText("ADD");
        getContentPane().add(jButton4);
        jButton4.setBounds(170, 210, 72, 23);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(250, 210, 170, 22);

        ImagemPulseFit.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\OneDrive\\Imagens\\PulseFit.jpg")); // NOI18N
        getContentPane().add(ImagemPulseFit);
        ImagemPulseFit.setBounds(70, 0, 970, 440);

        BotãoNotificação.setText("jButton2");
        BotãoNotificação.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotãoNotificação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoNotificaçãoActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoNotificação);
        BotãoNotificação.setBounds(150, 0, 30, 30);

        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 0, 870, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        TelaPrincipalHome Tela = new TelaPrincipalHome();
        Tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void IMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IMCActionPerformed

    private void TempoDeSonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempoDeSonoActionPerformed
        TelaPrincipalSono Tela = new TelaPrincipalSono();
        Tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TempoDeSonoActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        telaLogin Tela = new telaLogin();
        Tela.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void MedidorDeAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedidorDeAguaActionPerformed
        TelaPrincipalAgua Tela = new TelaPrincipalAgua();
        Tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MedidorDeAguaActionPerformed

    private void BotãoNotificaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoNotificaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotãoNotificaçãoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CalculadoraIMC Tela = new CalculadoraIMC();
        Tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Código para "Coloque sua altura abaixo"
        String altura = jTextField2.getText();
        if (altura.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "O campo de altura não pode estar vazio!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        inserirOuAtualizarInformacao("altura", altura);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Código para "Coloque seu peso abaixo"
        String peso = jTextField3.getText();
        if (peso.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "O campo de peso não pode estar vazio!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        inserirOuAtualizarInformacao("peso", peso);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void inserirOuAtualizarInformacao(String campo, String valor) {
        try {
            // Registrar o driver MariaDB
            Class.forName("org.mariadb.jdbc.Driver");

            // Conectar ao banco de dados
            try (java.sql.Connection conn = java.sql.DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/user_data", "root", "admin")) {

                // Verificar se o ID do usuário existe
                String verificaSQL = "SELECT COUNT(*) FROM users_information WHERE id = ?";
                try (java.sql.PreparedStatement verificaStmt = conn.prepareStatement(verificaSQL)) {
                    verificaStmt.setInt(1, GlobalVariables.getUserID());
                    try (java.sql.ResultSet rs = verificaStmt.executeQuery()) {
                        rs.next();
                        boolean existe = rs.getInt(1) > 0;

                        if (existe) {
                            // Atualizar o registro existente
                            String atualizaSQL = "UPDATE users_information SET " + campo + " = ? WHERE id = ?";
                            try (java.sql.PreparedStatement atualizaStmt = conn.prepareStatement(atualizaSQL)) {
                                atualizaStmt.setString(1, valor);
                                atualizaStmt.setInt(2, GlobalVariables.getUserID());
                                atualizaStmt.executeUpdate();
                            }
                        } else {
                            // Inserir novo registro
                            String insereSQL = "INSERT INTO users_information (id, " + campo + ") VALUES (?, ?)";
                            try (java.sql.PreparedStatement insereStmt = conn.prepareStatement(insereSQL)) {
                                insereStmt.setInt(1, GlobalVariables.getUserID());
                                insereStmt.setString(2, valor);
                                insereStmt.executeUpdate();
                            }
                        }
                    }
                }
            }

            // Exibir mensagem de sucesso
            javax.swing.JOptionPane.showMessageDialog(this, "Informação salva com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (java.sql.SQLException e) {
            // Exibir mensagem de erro em caso de falha
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException e) {
            // Exibir mensagem de erro se o driver não for encontrado
            javax.swing.JOptionPane.showMessageDialog(this, "Driver JDBC não encontrado: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }


    private boolean isCampoValido(String campo) {
        // Valide o campo contra uma lista de campos permitidos
        switch (campo) {
            case "nome":
            case "email":
            case "telefone":
                // Adicione outros campos permitidos conforme necessário
                return true;
            default:
                return false;
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AguaImagem;
    private javax.swing.JLabel AguaText1;
    private javax.swing.JLabel AguaText2;
    private javax.swing.JLabel AguaText3;
    private javax.swing.JButton BotãoNotificação;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel ExitImagem;
    private javax.swing.JPanel FundoParaTirarBorda;
    private javax.swing.JButton Home;
    private javax.swing.JLabel HomeImagen;
    private javax.swing.JLabel HomeText;
    private javax.swing.JButton IMC;
    private javax.swing.JLabel IMCImagem;
    private javax.swing.JLabel IMCText;
    private javax.swing.JLabel ImagemPulseFit;
    private javax.swing.JLabel ImagenNotificação;
    private javax.swing.JButton MedidorDeAgua;
    private javax.swing.JLabel SonoImagem;
    private javax.swing.JLabel SonoText1;
    private javax.swing.JLabel SonoText2;
    private javax.swing.JLabel SonoText3;
    private javax.swing.JButton TempoDeSono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}

// Classe GlobalVariables fora da TelaPrincipalIMC