/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaLogin;


import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
public class TelaPrincipal extends javax.swing.JFrame {
    
    private String[] mensagens;
    private int mensagemIndex;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        
        initComponents();
        mensagens = new String[]{
            "Lembre-se de beber água e fazer pausas regulares!",
            "Mantenha uma postura correta enquanto trabalha.",
            "Sua disposição aumenta quando você tem bons períodos de sono!",
            "Faça alguns alongamentos para evitar tensão muscular.",
            "Faça exercícios diariamente! Sua saúde agradeçe :) ",
            "Faça uma caminhada curta para melhorar a circulação."
        };
        mensagemIndex = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        FundoParaMouse4 = new javax.swing.JLabel();
        FundoParaMouse3 = new javax.swing.JLabel();
        FundoParaMouse2 = new javax.swing.JLabel();
        FundoParaMouse1 = new javax.swing.JLabel();
        HomeText = new javax.swing.JLabel();
        SonoText1 = new javax.swing.JLabel();
        SonoText2 = new javax.swing.JLabel();
        SonoText3 = new javax.swing.JLabel();
        AguaText1 = new javax.swing.JLabel();
        AguaText2 = new javax.swing.JLabel();
        AguaText3 = new javax.swing.JLabel();
        IMCText = new javax.swing.JLabel();
        HomeImagen = new javax.swing.JLabel();
        AguaImagem = new javax.swing.JLabel();
        IMCImagem = new javax.swing.JLabel();
        SonoImagem = new javax.swing.JLabel();
        ExitImagem = new javax.swing.JLabel();
        FundoParaTirarBorda = new javax.swing.JPanel();
        MedidorDeAgua = new javax.swing.JButton();
        IMC = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        TempoDeSono = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        FaleConoscoText = new javax.swing.JLabel();
        TelefoneText = new javax.swing.JLabel();
        EmailText = new javax.swing.JLabel();
        ImagenNotificação = new javax.swing.JLabel();
        ImagemPulseFit = new javax.swing.JLabel();
        BotãoNotificação = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PulseFit");
        setMinimumSize(new java.awt.Dimension(1050, 470));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        FundoParaMouse4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(FundoParaMouse4);
        FundoParaMouse4.setBounds(0, 280, 150, 60);

        FundoParaMouse3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(FundoParaMouse3);
        FundoParaMouse3.setBounds(0, 200, 150, 70);

        FundoParaMouse2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(FundoParaMouse2);
        FundoParaMouse2.setBounds(-30, 120, 180, 60);

        FundoParaMouse1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(FundoParaMouse1);
        FundoParaMouse1.setBounds(0, 46, 150, 60);

        HomeText.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        HomeText.setForeground(new java.awt.Color(0, 0, 0));
        HomeText.setText("Sobre nós");
        jPanel2.add(HomeText);
        HomeText.setBounds(70, 70, 90, 30);

        SonoText1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SonoText1.setForeground(new java.awt.Color(0, 0, 0));
        SonoText1.setText("Sono");
        jPanel2.add(SonoText1);
        SonoText1.setBounds(90, 320, 50, 20);

        SonoText2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SonoText2.setForeground(new java.awt.Color(0, 0, 0));
        SonoText2.setText("Gestão");
        jPanel2.add(SonoText2);
        SonoText2.setBounds(80, 280, 60, 20);

        SonoText3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SonoText3.setForeground(new java.awt.Color(0, 0, 0));
        SonoText3.setText("do");
        jPanel2.add(SonoText3);
        SonoText3.setBounds(100, 300, 20, 20);

        AguaText1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaText1.setForeground(new java.awt.Color(0, 0, 0));
        AguaText1.setText("Consumo ");
        jPanel2.add(AguaText1);
        AguaText1.setBounds(70, 190, 90, 40);

        AguaText2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaText2.setForeground(new java.awt.Color(0, 0, 0));
        AguaText2.setText("Água");
        AguaText2.setToolTipText("");
        jPanel2.add(AguaText2);
        AguaText2.setBounds(90, 240, 50, 30);

        AguaText3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaText3.setForeground(new java.awt.Color(0, 0, 0));
        AguaText3.setText("de");
        jPanel2.add(AguaText3);
        AguaText3.setBounds(100, 220, 30, 24);

        IMCText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IMCText.setForeground(new java.awt.Color(0, 0, 0));
        IMCText.setText("IMC");
        jPanel2.add(IMCText);
        IMCText.setBounds(90, 140, 40, 20);

        HomeImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\casa.png")); // NOI18N
        jPanel2.add(HomeImagen);
        HomeImagen.setBounds(10, 40, 60, 70);

        AguaImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\bebida.png")); // NOI18N
        jPanel2.add(AguaImagem);
        AguaImagem.setBounds(0, 200, 60, 64);

        IMCImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\balanca (3).png")); // NOI18N
        jPanel2.add(IMCImagem);
        IMCImagem.setBounds(10, 120, 60, 60);

        SonoImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\sono-suficiente.png")); // NOI18N
        SonoImagem.setToolTipText("");
        jPanel2.add(SonoImagem);
        SonoImagem.setBounds(10, 280, 70, 60);

        ExitImagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExitImagem.setForeground(new java.awt.Color(0, 0, 0));
        ExitImagem.setText("X");
        ExitImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(ExitImagem);
        ExitImagem.setBounds(10, 0, 10, 20);

        FundoParaTirarBorda.setBackground(new java.awt.Color(255, 255, 255));
        FundoParaTirarBorda.setForeground(new java.awt.Color(255, 255, 255));
        FundoParaTirarBorda.setLayout(null);
        jPanel2.add(FundoParaTirarBorda);
        FundoParaTirarBorda.setBounds(0, 0, 150, 500);

        MedidorDeAgua.setBackground(new java.awt.Color(255, 255, 255));
        MedidorDeAgua.setForeground(new java.awt.Color(0, 0, 0));
        MedidorDeAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        MedidorDeAgua.setBorderPainted(false);
        MedidorDeAgua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MedidorDeAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedidorDeAguaActionPerformed(evt);
            }
        });
        jPanel2.add(MedidorDeAgua);
        MedidorDeAgua.setBounds(0, 190, 150, 80);

        IMC.setBackground(new java.awt.Color(255, 255, 255));
        IMC.setForeground(new java.awt.Color(255, 255, 255));
        IMC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        IMC.setBorderPainted(false);
        IMC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCActionPerformed(evt);
            }
        });
        jPanel2.add(IMC);
        IMC.setBounds(0, 110, 150, 80);

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setBorder(null);
        Home.setBorderPainted(false);
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.setFocusPainted(false);
        Home.setNextFocusableComponent(HomeImagen);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel2.add(Home);
        Home.setBounds(0, 40, 150, 70);

        TempoDeSono.setBackground(new java.awt.Color(255, 255, 255));
        TempoDeSono.setForeground(new java.awt.Color(255, 255, 255));
        TempoDeSono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TempoDeSono.setBorderPainted(false);
        TempoDeSono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TempoDeSono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempoDeSonoActionPerformed(evt);
            }
        });
        jPanel2.add(TempoDeSono);
        TempoDeSono.setBounds(0, 270, 150, 80);

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setForeground(new java.awt.Color(0, 0, 0));
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ExitButton);
        ExitButton.setBounds(0, 0, 30, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 150, 680);

        FaleConoscoText.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        FaleConoscoText.setForeground(new java.awt.Color(0, 0, 0));
        FaleConoscoText.setText("Fale Conosco: ");
        getContentPane().add(FaleConoscoText);
        FaleConoscoText.setBounds(150, 360, 160, 20);

        TelefoneText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TelefoneText.setForeground(new java.awt.Color(0, 0, 0));
        TelefoneText.setText("Telefone: +55(11)93146-8446");
        getContentPane().add(TelefoneText);
        TelefoneText.setBounds(150, 380, 220, 20);

        EmailText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EmailText.setForeground(new java.awt.Color(0, 0, 0));
        EmailText.setText("Email: Pulsefit32@Biotech.com");
        getContentPane().add(EmailText);
        EmailText.setBounds(150, 400, 220, 17);

        ImagenNotificação.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\Downloads\\cuidado (1).png")); // NOI18N
        ImagenNotificação.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(ImagenNotificação);
        ImagenNotificação.setBounds(150, 0, 32, 30);

        ImagemPulseFit.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\OneDrive\\Imagens\\PulseFit.jpg")); // NOI18N
        getContentPane().add(ImagemPulseFit);
        ImagemPulseFit.setBounds(80, 0, 950, 440);

        BotãoNotificação.setText("jButton2");
        BotãoNotificação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoNotificaçãoActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoNotificação);
        BotãoNotificação.setBounds(150, 0, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
TelaPrincipalHome Tela = new TelaPrincipalHome();
        Tela.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_HomeActionPerformed

    private void IMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCActionPerformed
TelaPrincipalIMC Tela = new TelaPrincipalIMC();
        Tela.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_IMCActionPerformed

    private void TempoDeSonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempoDeSonoActionPerformed
TelaPrincipalSono Tela = new TelaPrincipalSono();
        Tela.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TempoDeSonoActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
 telaLogin Tela = new telaLogin();
        Tela.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void MedidorDeAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedidorDeAguaActionPerformed
TelaPrincipalAgua Tela = new TelaPrincipalAgua();
        Tela.setVisible(true);
        this.dispose();    }//GEN-LAST:event_MedidorDeAguaActionPerformed

    private void BotãoNotificaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoNotificaçãoActionPerformed
            Timer timer = new Timer(30000, new ActionListener() {
            
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, mensagens[mensagemIndex]);
                mensagemIndex = (mensagemIndex + 1) % mensagens.length;
            }
        });
        timer.start();
        JOptionPane.showMessageDialog(null, "Notificações ativadas!");        // TODO add your handling code here:
    }//GEN-LAST:event_BotãoNotificaçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AguaImagem;
    private javax.swing.JLabel AguaText1;
    private javax.swing.JLabel AguaText2;
    private javax.swing.JLabel AguaText3;
    private javax.swing.JButton BotãoNotificação;
    private javax.swing.JLabel EmailText;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel ExitImagem;
    private javax.swing.JLabel FaleConoscoText;
    private javax.swing.JLabel FundoParaMouse1;
    private javax.swing.JLabel FundoParaMouse2;
    private javax.swing.JLabel FundoParaMouse3;
    private javax.swing.JLabel FundoParaMouse4;
    private javax.swing.JPanel FundoParaTirarBorda;
    private javax.swing.JButton Home;
    private javax.swing.JLabel HomeImagen;
    private javax.swing.JLabel HomeText;
    private javax.swing.JButton IMC;
    private javax.swing.JLabel IMCImagem;
    private javax.swing.JLabel IMCText;
    private javax.swing.JLabel ImagemPulseFit;
    private javax.swing.JLabel ImagenNotificação;
    private javax.swing.JButton MedidorDeAgua;
    private javax.swing.JLabel SonoImagem;
    private javax.swing.JLabel SonoText1;
    private javax.swing.JLabel SonoText2;
    private javax.swing.JLabel SonoText3;
    private javax.swing.JLabel TelefoneText;
    private javax.swing.JButton TempoDeSono;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
