/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaLogin;

import TelaLogin.telaLogin;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author unive
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroBotão = new javax.swing.JButton();
        VoltarBotão = new javax.swing.JButton();
        JUsuarioTextField = new javax.swing.JTextField();
        JSenhaField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JLabel();
        SenhaText = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        ImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaCadastro");
        setMinimumSize(new java.awt.Dimension(514, 445));
        getContentPane().setLayout(null);

        CadastroBotão.setText("Cadastar");
        CadastroBotão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBotãoActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroBotão);
        CadastroBotão.setBounds(300, 360, 80, 23);

        VoltarBotão.setText("Voltar");
        VoltarBotão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBotãoActionPerformed(evt);
            }
        });
        getContentPane().add(VoltarBotão);
        VoltarBotão.setBounds(400, 360, 80, 23);
        getContentPane().add(JUsuarioTextField);
        JUsuarioTextField.setBounds(310, 130, 160, 30);
        getContentPane().add(JSenhaField);
        JSenhaField.setBounds(310, 189, 160, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email*:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 230, 120, 19);

        UsuarioText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        UsuarioText.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioText.setText("Usuario*:");
        getContentPane().add(UsuarioText);
        UsuarioText.setBounds(310, 110, 70, 19);

        SenhaText.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SenhaText.setForeground(new java.awt.Color(255, 255, 255));
        SenhaText.setText("Senha*:");
        getContentPane().add(SenhaText);
        SenhaText.setBounds(310, 170, 60, 20);

        Titulo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("BioTech");
        getContentPane().add(Titulo);
        Titulo.setBounds(10, 20, 190, 130);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF*:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 290, 60, 19);

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(310, 250, 160, 30);
        getContentPane().add(jTextFieldCPF);
        jTextFieldCPF.setBounds(310, 310, 160, 30);

        ImagemFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\unive\\OneDrive\\Imagens\\960x0.jpg")); // NOI18N
        getContentPane().add(ImagemFundo);
        ImagemFundo.setBounds(-290, -20, 820, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBotãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBotãoActionPerformed
        telaLogin Tela = new telaLogin();
        Tela.setVisible(true);
        this.dispose();        // TOD        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarBotãoActionPerformed

    private void CadastroBotãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBotãoActionPerformed
        // Obter os valores dos campos
        String usuario = JUsuarioTextField.getText();
        String senha = new String(JSenhaField.getPassword());
        String email = jTextFieldEmail.getText();
        String cpf = jTextFieldCPF.getText();

        // Verificar se todos os campos estão preenchidos
        if (usuario.isEmpty() || senha.isEmpty() || email.isEmpty() || cpf.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos os campos precisam ser preenchidos!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Conectar ao banco de dados e inserir os dados
        try {
            // Conectar ao banco de dados
            java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/user_data", "root", "admin");

            // Preparar a inserção dos dados
            String sql = "INSERT INTO users_login (usuario, senha, email, cpf) VALUES (?, ?, ?, ?)";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, usuario);
            stmt.setString(2, senha);
            stmt.setString(3, email);
            stmt.setString(4, cpf);

            // Executar a inserção
            stmt.executeUpdate();

            // Fechar a conexão
            stmt.close();
            conn.close();

            // Exibir mensagem de sucesso
            javax.swing.JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Redirecionar para a tela de login
            telaLogin Tela = new telaLogin();
            Tela.setVisible(true);
            this.dispose();

        } catch (java.sql.SQLException e) {
            // Exibir mensagem de erro em caso de falha
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CadastroBotãoActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

   
   

    public JPasswordField getJSenhaField() {
        return JSenhaField;
    }

    public void setJSenhaField(JPasswordField JSenhaField) {
        this.JSenhaField = JSenhaField;
    }

    public JTextField getJUsuarioTextField() {
        return JUsuarioTextField;
    }

    public void setJUsuarioTextField(JTextField JUsuarioTextField) {
        this.JUsuarioTextField = JUsuarioTextField;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public JTextField getjTextFieldCPF() {
        return jTextFieldCPF;
    }

    public void setjTextFieldCPF(JTextField jTextFieldCPF) {
        this.jTextFieldCPF = jTextFieldCPF;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroBotão;
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JPasswordField JSenhaField;
    private javax.swing.JTextField JUsuarioTextField;
    private javax.swing.JLabel SenhaText;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel UsuarioText;
    private javax.swing.JButton VoltarBotão;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
